In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [3]:
import string

In [4]:
df_fake = pd.read_csv('../fake_news_detection/Fake.csv')
df_true = pd.read_csv('../fake_news_detection/True.csv')

In [5]:
df_fake.shape, df_true.shape

((23481, 4), (21417, 4))

In [6]:
df_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [7]:
df_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [8]:
df_fake["target"]=0
df_true["target"]=1

In [9]:
df_fake.head(), df_true.head()

(                                               title  \
 0   Donald Trump Sends Out Embarrassing New Year’...
 1   Drunk Bragging Trump Staffer Started Russian ...
 2   Sheriff David Clarke Becomes An Internet Joke...
 3   Trump Is So Obsessed He Even Has Obama’s Name...
 4   Pope Francis Just Called Out Donald Trump Dur...

                                                 text subject  \
 0  Donald Trump just couldn t wish all Americans ...    News
 1  House Intelligence Committee Chairman Devin Nu...    News
 2  On Friday, it was revealed that former Milwauk...    News
 3  On Christmas day, Donald Trump announced that ...    News
 4  Pope Francis used his annual Christmas Day mes...    News

                 date  target
 0  December 31, 2017       0
 1  December 31, 2017       0
 2  December 30, 2017       0
 3  December 29, 2017       0
 4  December 25, 2017       0  ,
                                                title  \
 0  As U.S. budget fight looms, Republicans flip t...
 1  U.S. military to accept transgender recruits o...
 2  Senior U.S. Republican senator: 'Let Mr. Muell...
 3  FBI Russia probe helped by Australian diplomat...
 4  Trump wants Postal Service to charge 'much mor...

                                                 text       subject  \
 0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews
 1  WASHINGTON (Reuters) - Transgender people will...  politicsNews
 2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews
 3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews
 4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews

                  date  target
 0  December 31, 2017        1
 1  December 29, 2017        1
 2  December 31, 2017        1
 3  December 30, 2017        1
 4  December 29, 2017        1  )

In [10]:
df = pd.concat([df_fake, df_true], axis=0)

In [11]:
df = df.sample(frac=1)

In [12]:
df.reset_index(drop=True, inplace=True)

In [13]:
df.isnull().sum()

title      0
text       0
subject    0
date       0
target     0
dtype: int64

In [14]:
df.columns

Index(['title', 'text', 'subject', 'date', 'target'], dtype='object')

In [15]:
df=df.drop(columns=['title', 'subject', 'date'], axis=1)

In [16]:
df.head()

                                                text  target
0  WASHINGTON (Reuters) - The U.S. House of Repre...       1
1  White House counselor Kellyanne Conway crawled...       0
2  SEOUL (Reuters) - The South Korean president s...       1
3  WASHINGTON (Reuters) - The U.S. Senate voted o...       1
4  Independent voter Chris Sullivan went to the p...       0

In [17]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\chauh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [18]:
ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

In [19]:
def transform_text(text):
    text = text.lower()
    text = nltk.word_tokenize(text)

    y = []

    for i in text:
        if i.isalnum() and i not in stop_words:
            y.append(ps.stem(i))
    return ' '.join(y)

In [20]:
df['text'] = df['text'].apply(transform_text)

In [21]:
corpus = df['text'].tolist()

In [22]:
corpus[0]

'washington reuter hous repres pass two piec legisl link intern nuclear agreement iran thursday one year landmark pact announc defi presid barack obama veto threat vote larg along parti line hous vote 246 179 pass new set sanction iran 246 181 measur block iran access financi system includ use dollar hous wednesday pass bill bar purchas heavi water also littl back democrat heavi water byproduct make nuclear weapon nuclear energi obama administr said april unit state would buy million worth heavi water iran anger republican call subsidi countri nuclear program measur among last hous pass congress left washington summer recess word whether measur would taken senat everi congression republican sever obama fellow democrat oppos nuclear deal iran unit state world power announc juli 2015 tehran agre curtail nuclear program exchang relief crippl intern sanction sinc republican repeatedli offer sanction bill legisl democrat dismiss bid score polit point undermin deal seen potenti foreign polici legaci obama republican say want punish iran action includ ballist missil test send strong messag tehran abid intern commit'

In [23]:
from tensorflow.keras.preprocessing.text import one_hot

In [24]:
vec_size=5000
onehot_rep = [one_hot(words, vec_size) for words in corpus]

In [25]:
onehot_rep[0]

[3597,
 4940,
 583,
 4575,
 3380,
 4201,
 4282,
 4454,
 3666,
 2247,
 4961,
 4425,
 3392,
 468,
 3490,
 953,
 2120,
 1270,
 803,
 4234,
 1571,
 2274,
 3801,
 4953,
 2543,
 1077,
 1597,
 1680,
 2434,
 783,
 583,
 1077,
 4616,
 562,
 3380,
 2742,
 1416,
 4109,
 3392,
 4616,
 3339,
 131,
 512,
 3392,
 2845,
 4550,
 4538,
 2922,
 4752,
 3374,
 583,
 2998,
 3380,
 971,
 4139,
 3060,
 3955,
 878,
 1700,
 1558,
 3779,
 1538,
 3955,
 878,
 4685,
 2632,
 4961,
 4806,
 4961,
 2382,
 3801,
 2384,
 2565,
 1936,
 4405,
 4729,
 3158,
 53,
 4647,
 257,
 3955,
 878,
 3392,
 1396,
 31,
 50,
 2875,
 2260,
 4961,
 2313,
 131,
 3199,
 2921,
 583,
 3380,
 2855,
 1021,
 3597,
 2641,
 2072,
 4824,
 2775,
 131,
 3158,
 1615,
 1014,
 3567,
 576,
 31,
 4496,
 3801,
 793,
 1538,
 1048,
 4961,
 3128,
 3392,
 4405,
 4729,
 175,
 1232,
 803,
 1574,
 3687,
 3029,
 3891,
 4555,
 4961,
 2313,
 3161,
 3083,
 1348,
 2247,
 4109,
 1565,
 31,
 2500,
 1278,
 4109,
 971,
 4454,
 1538,
 3738,
 4444,
 2171,
 1421,
 4751,
 2228,
 3128,
 1953,
 2301,
 653,
 4470,
 82,
 3801,
 31,
 1943,
 4267,
 2110,
 3392,
 1483,
 2922,
 3324,
 1099,
 1970,
 1231,
 1090,
 1037,
 3029,
 3708,
 2247,
 4762]

In [31]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM

In [36]:
## embedding representation

sent_length=300
embedded_doc = pad_sequences(onehot_rep, padding='post', maxlen=sent_length)

In [37]:
embedded_doc[0]

array([3597, 4940,  583, 4575, 3380, 4201, 4282, 4454, 3666, 2247, 4961,
       4425, 3392,  468, 3490,  953, 2120, 1270,  803, 4234, 1571, 2274,
       3801, 4953, 2543, 1077, 1597, 1680, 2434,  783,  583, 1077, 4616,
        562, 3380, 2742, 1416, 4109, 3392, 4616, 3339,  131,  512, 3392,
       2845, 4550, 4538, 2922, 4752, 3374,  583, 2998, 3380,  971, 4139,
       3060, 3955,  878, 1700, 1558, 3779, 1538, 3955,  878, 4685, 2632,
       4961, 4806, 4961, 2382, 3801, 2384, 2565, 1936, 4405, 4729, 3158,
         53, 4647,  257, 3955,  878, 3392, 1396,   31,   50, 2875, 2260,
       4961, 2313,  131, 3199, 2921,  583, 3380, 2855, 1021, 3597, 2641,
       2072, 4824, 2775,  131, 3158, 1615, 1014, 3567,  576,   31, 4496,
       3801,  793, 1538, 1048, 4961, 3128, 3392, 4405, 4729,  175, 1232,
        803, 1574, 3687, 3029, 3891, 4555, 4961, 2313, 3161, 3083, 1348,
       2247, 4109, 1565,   31, 2500, 1278, 4109,  971, 4454, 1538, 3738,
       4444, 2171, 1421, 4751, 2228, 3128, 1953, 2301,  653, 4470,   82,
       3801,   31, 1943, 4267, 2110, 3392, 1483, 2922, 3324, 1099, 1970,
       1231, 1090, 1037, 3029, 3708, 2247, 4762,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0], dtype=int32)

In [52]:
## Create Model 

embedding_vector_features = 50
model=Sequential()
model.add(Embedding(vec_size, 
                    embedding_vector_features,
                    input_length=sent_length))
model.add(LSTM(50))
model.add(Dense(
    1,
    activation='sigmoid'
))

C:\Users\chauh\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [53]:
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']

)

In [54]:
print(model.summary())

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [55]:
X = df.drop(columns=['target'], axis=1)
y = df['target']

In [56]:
len(embedded_doc),y.shape

(44898, (44898,))

In [57]:
X_final = np.array(embedded_doc)
y_final = np.array(y)

In [58]:
##train test split

X_train, X_test, y_train, y_test = train_test_split(X_final,y_final,test_size=0.33, random_state=42)

In [59]:
## final Tunning

model.fit(
    X_train, 
    y_train,
    validation_data=(
        X_test,
        y_test
    ),
    epochs=10,
    batch_size=128
)

Epoch 1/10
236/236 ━━━━━━━━━━━━━━━━━━━━ 129s 520ms/step - accuracy: 0.6224 - loss: 0.6326 - val_accuracy: 0.5705 - val_loss: 0.5808
Epoch 2/10
236/236 ━━━━━━━━━━━━━━━━━━━━ 125s 529ms/step - accuracy: 0.6435 - loss: 0.5863 - val_accuracy: 0.7348 - val_loss: 0.5212
Epoch 3/10
236/236 ━━━━━━━━━━━━━━━━━━━━ 145s 541ms/step - accuracy: 0.8697 - loss: 0.3789 - val_accuracy: 0.9417 - val_loss: 0.2166
Epoch 4/10
236/236 ━━━━━━━━━━━━━━━━━━━━ 126s 536ms/step - accuracy: 0.8990 - loss: 0.3026 - val_accuracy: 0.9360 - val_loss: 0.2299
Epoch 5/10
236/236 ━━━━━━━━━━━━━━━━━━━━ 128s 544ms/step - accuracy: 0.9454 - loss: 0.1999 - val_accuracy: 0.9447 - val_loss: 0.2093
Epoch 6/10
236/236 ━━━━━━━━━━━━━━━━━━━━ 129s 546ms/step - accuracy: 0.9199 - loss: 0.2565 - val_accuracy: 0.9105 - val_loss: 0.2855
Epoch 7/10
236/236 ━━━━━━━━━━━━━━━━━━━━ 132s 559ms/step - accuracy: 0.9266 - loss: 0.2457 - val_accuracy: 0.9224 - val_loss: 0.2541
Epoch 8/10
236/236 ━━━━━━━━━━━━━━━━━━━━ 129s 547ms/step - accuracy: 0.9289 - loss: 0.2396 - val_accuracy: 0.9274 - val_loss: 0.2424
Epoch 9/10
236/236 ━━━━━━━━━━━━━━━━━━━━ 128s 542ms/step - accuracy: 0.9336 - loss: 0.2267 - val_accuracy: 0.9155 - val_loss: 0.2767
Epoch 10/10
236/236 ━━━━━━━━━━━━━━━━━━━━ 131s 557ms/step - accuracy: 0.9277 - loss: 0.2379 - val_accuracy: 0.9027 - val_loss: 0.3160

In [65]:
y_pred=model.predict(X_test)

464/464 ━━━━━━━━━━━━━━━━━━━━ 49s 74ms/step

In [66]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [67]:
from sklearn.metrics import confusion_matrix

In [68]:
confusion_matrix(y_test,y_pred)

array([[7263,  467],
       [1020, 6067]])

In [69]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8996423027603428

In [70]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.94      0.91      7730
           1       0.93      0.86      0.89      7087

    accuracy                           0.90     14817
   macro avg       0.90      0.90      0.90     14817
weighted avg       0.90      0.90      0.90     14817

In [71]:
import pickle

In [75]:
model.save("model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [76]:
import pickle

config = {
    "vec_size": 5000,
    "sent_length": 300
}

with open("config.pkl", "wb") as f:
    pickle.dump(config, f)

In [72]:
model.save("model.keras")

In [ ]:
pickle.dump(tokenizer, open('tokenizer.pkl', 'wb'))